#!/usr/bin/env python3
"""
Codegen: read every backend/engine/nodes/*.yaml and emit a single TypeScript
specs file consumed by the TS api-server. The Python YAMLs are the SINGLE
source of truth for node metadata across BOTH backends.

Run from the workspace root via:
    pnpm --filter @workspace/api-server run gen:specs

Output:
    artifacts/api-server/src/nodes/specs.generated.ts
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
YAML_DIR = ROOT / "python-backend" / "backend" / "engine" / "nodes"
OUT = ROOT / "artifacts" / "api-server" / "src" / "nodes" / "specs.generated.ts"


def load_specs() -> list[dict]:
    specs: list[dict] = []
    for yml in sorted(YAML_DIR.glob("*.yaml")):
        raw = yaml.safe_load(yml.read_text())
        if not isinstance(raw, dict) or "type_id" not in raw:
            continue
        # Normalise: ensure all fields are present + JSON-friendly
        spec = {
            "typeId":      raw["type_id"],
            "description": raw.get("description", ""),
            "ui": {
                "displayName": (raw.get("ui") or {}).get("display_name", raw["type_id"].replace("_", " ").title()),
                "icon":        (raw.get("ui") or {}).get("icon", "Box"),
                "color":       (raw.get("ui") or {}).get("color", "#7c3aed"),
                "category":    (((raw.get("ui") or {}).get("palette") or {}).get("section") or {}).get("id", "other"),
            },
            "inputPorts":  list(raw.get("input_ports") or []),
            "outputPorts": list(raw.get("output_ports") or []),
            "params":      list(raw.get("params") or []),
        }
        specs.append(spec)
    return specs


HEADER = '''// AUTO-GENERATED by python-backend/scripts/gen_ts_specs.py from
// python-backend/backend/engine/nodes/*.yaml — DO NOT EDIT BY HAND.
// Re-run: `pnpm --filter @workspace/api-server run gen:specs`

import type { NodeSpec } from "./types.js";

export const NODE_SPECS: NodeSpec[] = '''


def main() -> int:
    if not YAML_DIR.exists():
        print(f"YAML dir not found: {YAML_DIR}", file=sys.stderr)
        return 1
    specs = load_specs()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(specs, indent=2, ensure_ascii=False)
    OUT.write_text(HEADER + body + " as const;\n")
    print(f"Wrote {len(specs)} specs → {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
